Algoritmo "calcule_quadrado_exercicio2"

Var
 n1,n2,n3,n4: inteiro
 soma, result: real

Inicio
 escreval("Digite o valor do numero 1: ")
 leia(n1)
 escreval("Digite o valor do numero 2: ")
 leia(n2)
 escreval("Digite o valor do numero 3: ")
 leia(n3)
 escreval("Digite o valor do numero 4 ")
 leia(n4)
 soma <- n1 * n1 + n2 * n2 + n3 * n3 + n4 *n4
 result <- soma
 
 escreval("o resultado é:",result)


Fimalgoritmo